<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input end Period</name>
   <tag></tag>
   <elementGuidId>5f990839-b333-4ea1-8ed5-c02a5281c650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc4f5d05-b224-4415-95f2-f46296007745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4873512-2462-46cf-b238-5e98a1823ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>27e6d154-67f9-4f5f-8592-9b8c713e7c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-medium text-sm w-full text-sm px-2 border border-grey-80 rounded disabled:bg-neutral-80 disabled:cursor-disabled w-full border border-grey-80 px-2 text-[0.8125rem] shadow-sm</value>
      <webElementGuid>57e54922-4270-42ee-80e8-b9d7a03ce6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;relative w-full overflow-x-hidden md:ml-64  ml-0 h-[calc(100vh-64px)] top-16 bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;relative&quot;]/section[@class=&quot;space-y-6&quot;]/div[2]/div[1]/form[1]/div[@class=&quot;grid grid-cols-3 gap-6 lg:grid-cols-6 xl:grid-cols-5&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md col-span-3 flex flex-col space-y-4&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;relative flex space-x-3 pt-3.5 pl-7 before:absolute before:left-1.5 before:top-0 before:h-14 before:w-4 before:border-l before:border-b before:border-[#BDBDBD]&quot;]/div[@class=&quot;flex w-full flex-col space-y-4&quot;]/div[@class=&quot;flex space-x-4&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;react-datepicker-wrapper bg-black&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/input[@class=&quot;font-medium text-sm w-full text-sm px-2 border border-grey-80 rounded disabled:bg-neutral-80 disabled:cursor-disabled w-full border border-grey-80 px-2 text-[0.8125rem] shadow-sm&quot;]</value>
      <webElementGuid>c4737ffc-071a-4294-9ff9-5486dac37a64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[5]</value>
      <webElementGuid>60b2e6f4-3862-4336-a2bb-e7077248684e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/section/div[2]/div/form/div/div/div[5]/div[4]/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>81425039-7004-4963-93b8-7331d1522ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>53ebb709-c3f9-49de-9f48-09f641436d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>ac6d763b-9fb3-496c-891f-5b3b9a435c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
