<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Recurring input_Amount_transactionScheduleType</name>
   <tag></tag>
   <elementGuidId>5d361fb7-51d1-493c-8abe-af55d709db07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='transactionScheduleType'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>213ebd72-ef63-41a2-a993-ab20f50e486a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>59f42d08-e1bf-4c8b-8221-75ee0c5c20b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionScheduleType</value>
      <webElementGuid>0ad4fa98-3175-44f9-8cfb-c72f9bfe9867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;relative w-full overflow-x-hidden md:ml-64  ml-0 h-[calc(100vh-64px)] top-16 bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;relative&quot;]/section[@class=&quot;space-y-6&quot;]/div[2]/div[1]/form[1]/div[@class=&quot;grid grid-cols-3 gap-6 lg:grid-cols-6 xl:grid-cols-5&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md col-span-3 flex flex-col space-y-4&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;flex items-center space-x-3 py-1.5&quot;]/input[1]</value>
      <webElementGuid>5aef9bdc-aec4-4458-9149-d6df67f9bf22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='transactionScheduleType'])[3]</value>
      <webElementGuid>b35419bd-6543-42f1-8b65-99b368cf5dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/section/div[2]/div/form/div/div/div[5]/div[3]/input</value>
      <webElementGuid>4826dbcb-3119-4883-b6f1-3fe6063fdb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/input</value>
      <webElementGuid>5c79a48a-78fd-486f-996e-c343d52b2ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'transactionScheduleType']</value>
      <webElementGuid>37fff835-94d0-44c9-8572-c8388bde1385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
