<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DEDY YUSUF SILABAN - 037901005847535</name>
   <tag></tag>
   <elementGuidId>70c22463-e1b2-4b3d-b39c-757b49227e12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-senderAccountNumber-option-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-senderAccountNumber-option-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3d22467-a13f-4521-80f4-7a110c406312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-1n7v3ny-option</value>
      <webElementGuid>0b86a264-23df-4e80-be13-72ac60c1de64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e2375d9d-2ce2-4570-b12d-94ac957d0451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-senderAccountNumber-option-6</value>
      <webElementGuid>870a09f1-75a4-4bad-ae18-c313cd60b288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>304faa21-7ff1-4963-8dc7-fa238dc311f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DEDY YUSUF SILABAN - 037901005847535</value>
      <webElementGuid>ee6ca8ce-f7dd-4353-a780-abf40a834b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-senderAccountNumber-option-6&quot;)</value>
      <webElementGuid>46b66e19-4c30-417b-af60-4c7d3da1ed5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-senderAccountNumber-option-6']</value>
      <webElementGuid>19228195-8552-46c0-9d75-274e4c8005fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-senderAccountNumber-listbox']/div/div[7]</value>
      <webElementGuid>d95041fd-e05d-4b6e-9531-2257604fa5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUTIARA AGHNYN AISYA - 001201182874500'])[1]/following::div[1]</value>
      <webElementGuid>9a7028cf-df6e-444a-a9ee-c0c62b3a22d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANGGA FITHRA WARDHAN - 020603000001509'])[1]/following::div[2]</value>
      <webElementGuid>685f9215-4499-4c82-9287-e55052426345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INTERFERRO MANGANDO - 020602000029307'])[1]/preceding::div[1]</value>
      <webElementGuid>e7c6459f-d3dd-4882-b750-45828d2d8bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LARASATI DIAH INDRIA - 001201183100506'])[1]/preceding::div[2]</value>
      <webElementGuid>9f957b5e-31ab-4020-9bcc-699eb7d0b355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DEDY YUSUF SILABAN - 037901005847535']/parent::*</value>
      <webElementGuid>1db3f9e2-1977-4a2c-af68-2e8575521e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[7]</value>
      <webElementGuid>dda99ec0-a30a-450e-9e29-9ffd81d7a08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-senderAccountNumber-option-6' and (text() = 'DEDY YUSUF SILABAN - 037901005847535' or . = 'DEDY YUSUF SILABAN - 037901005847535')]</value>
      <webElementGuid>13859fbe-940b-4d90-a0ca-93111c26e77d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
