<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password_login</name>
   <tag></tag>
   <elementGuidId>ea6a15ed-212d-46af-a16d-eb74aba3e74c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc32bc98-9ba5-4b77-957c-6070d8c5a203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0e0b6f75-b334-4280-861c-c4be38d814f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> focus:ring-1 hover:ring-primary-70  focus:ring-primary-70 focus:border-primary-70  block sm:text-sm border-neutral-70 border shadow-sm px-2 h-8 text-neutral-10 caret-primary-70 rounded w-full hover:outline-offset-0 disabled:bg-grey-90 disabled:cursor-not-allowed</value>
      <webElementGuid>92ca6cd3-ce5a-4ff5-86f8-5e5e028bc729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>******</value>
      <webElementGuid>53b6dd8a-1890-4a23-9662-1f7c6cf0bd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex h-screen w-full flex-col items-center justify-center overflow-y-auto bg-primary-50 p-4&quot;]/div[@class=&quot;mx-auto h-[424px] w-full rounded bg-white px-8 py-8 shadow-md sm:w-96&quot;]/form[1]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;focus:ring-1 hover:ring-primary-70  focus:ring-primary-70 focus:border-primary-70  block sm:text-sm border-neutral-70 border shadow-sm px-2 h-8 text-neutral-10 caret-primary-70 rounded w-full hover:outline-offset-0 disabled:bg-grey-90 disabled:cursor-not-allowed&quot;]</value>
      <webElementGuid>9fdee233-34ab-474a-9128-a0739caead83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>dc5eeee6-c052-4afc-a996-719c2e22f909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/form/div[2]/div/input</value>
      <webElementGuid>587e5861-e28f-48d1-937a-6e149419f882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3da14e56-b2c9-413d-883d-d081d3631637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = '******']</value>
      <webElementGuid>563ede87-2549-4d39-8220-a3fddaf4aa17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
