<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pop Out Single Transfer</name>
   <tag></tag>
   <elementGuidId>56141532-f912-4bfa-b8c1-67e3e7fabbbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-:r13:']/div[2]/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.h-32.w-64.rounded.border.p-4.flex.cursor-pointer.flex-col.justify-between.border-grey-70</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9d077be2-e431-4dca-9b80-c83b045cc3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-32 w-64 rounded border p-4 flex cursor-pointer flex-col justify-between border-grey-70</value>
      <webElementGuid>942445c4-73f1-46f3-8cbe-b0d954c35caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single Transfer</value>
      <webElementGuid>ccd2c720-608a-4d3e-bf5a-8a62d8715706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-:r13:&quot;)/div[@class=&quot;absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 min-w-120 bg-white p-8 shadow-md rounded text-sm w-max opacity-100 scale-100&quot;]/div[@class=&quot;mb-6 grid grid-cols-2 gap-4&quot;]/div[@class=&quot;h-32 w-64 rounded border p-4 flex cursor-pointer flex-col justify-between border-grey-70&quot;]</value>
      <webElementGuid>306f01d8-387a-471d-9700-052b2dffd68d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-:r13:']/div[2]/div[3]/div</value>
      <webElementGuid>36dc0e66-d758-4338-8477-c1d8d0bb8bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Transfer - BRI to BRI'])[1]/following::div[3]</value>
      <webElementGuid>abece755-942f-41d2-bfa6-138c32b7e027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[11]</value>
      <webElementGuid>c06157d7-d693-430c-8f2d-d8ffbf11c7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multiple Transfer'])[1]/preceding::div[5]</value>
      <webElementGuid>d4acde09-2391-4e02-b53d-22033ed07a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[3]/div</value>
      <webElementGuid>52f583e4-9f65-4997-b159-b8a6e576862c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Single Transfer' or . = 'Single Transfer')]</value>
      <webElementGuid>e0991e94-4823-4e94-b2b3-23b43035b281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
